[build]
builder = "nixpacks"
buildCommand = "go build -o bin/app cmd/server/main.go"

[deploy]
startCommand = "./bin/app"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"

[env]
ENV = "production"
ALLOWED_ORIGINS = "https://<your-railway-domain>.railway.app"  # Replace with your actual domain
