[build]
builder = "nixpacks"
buildCommand = "go build -o bin/app ./cmd/server"

[deploy]
startCommand = "./bin/app"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[env]
ENV = "production"
ALLOWED_ORIGINS = "https://zeem-be-production.up.railway.app"  # Replace with your actual domain
